name: Stop OVH VM

on:
  workflow_dispatch:
    inputs:
      instance_name:
        description: 'Instance name (will be prefixed with github-action-vm)'
        required: true
        type: string

jobs:
  stop-vm:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '23.7.0'

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Stop VM
        run: node src/stop.ts
        env:
          OVH_ENDPOINT: ${{ vars.OVH_ENDPOINT }}
          OVH_APPLICATION_KEY: ${{ secrets.OVH_APPLICATION_KEY }}
          OVH_APPLICATION_SECRET: ${{ secrets.OVH_APPLICATION_SECRET }}
          OVH_CONSUMER_KEY: ${{ secrets.OVH_CONSUMER_KEY }}
          OVH_SERVICE_NAME: ${{ secrets.OVH_SERVICE_NAME }}
          INSTANCE_NAME: github-action-vm-${{ inputs.instance_name }}
